var txt1 = document.getElementById("texto1");
var txt2 = document.getElementById("texto2");
var txt3 = document.getElementById("texto3");
var txt4 = document.getElementById("nombre");
console.log(txt1);
console.log(txt2);
console.log(txt4);
txt1.textContent="Universidad";
txt2.textContent="Los limones";
txt3.textContent= txt1.textContent+ " "+ txt2.textContent;